### ISSUE TITLE
有些疑问

### ISSUE THREAD

**Issue by Somnusochi** [MMF-FE/weex-vue-navigator#2]
* 当在iOS上使用weex-vue-navigator时，我底部放了4个navbar，然后不断点击切换navbar或者说连续不断点击某一个navbar按钮，应用会不断打开新页面，然后最后会内存泄露，应用会闪退，有什么好的方法或思路解决么？
* 还有jumpOnSelf具体是在什么时候可以用呢？我在我的应用路由上使用jumpOnSelf的结果是直接白屏

**Comment by vfasky** [comment]
抱歉，变量名没起好。应该叫 openOnSelf 。就是给 Tab 这种场景用的。 

别，能贴一下导致白屏的代码吗？

**Comment by Somnusochi** [comment]
嗯，白屏我觉得应该是我这个项目的代码有点问题，原来的项目是`Vue2`的，然后业务需要要出客户端，然后用了`weex`，我拿那个`HackerNews`的项目的脚手架改的，我按`HackerNews`里面那样的直接路由跳转就是`xcode`显示`update Finish`，但是页面没有任何变化，不知道为什么，嗯，如果方便可以加下QQ或者什么的，帮我看一下么？万分感谢

**Comment by vfasky** [comment]
@Somnusochi 抱歉，暂时只有精力解决 `weex-vue-navigator` 插件的问题. 望理解。

**Comment by Somnusochi** [comment]
嗯，那好吧，感谢
